#https://www.rubydoc.info/gems/slather/2.7.4

coverage_service: html
xcodeproj: ./github-person.xcodeproj
scheme: unit-tests
configuration: Debug
source_directory: ./source
output_directory: ./CodeCoverageReport
binary-basename: github-personTests
ignore: 
- ../../Library/Developer/Xcode/DerivedData/**/SourcePackages/*
- "**/AppDelegate.swift"
- "**/SceneDelegate.swift"